### ISSUE TITLE
Suppresses 500 error output

### ISSUE THREAD

**Issue by revmischa** [level12/flask-webtest#13]
If I use app.test_client() and make a get() to a URL that causes a 500, I see the error output and stack trace.

If I use flask_webtest, I only see the 500 error but I don't see the stack trace of what the error was.
I think this is the reason: https://github.com/aromanovich/flask-webtest/blob/master/flask_webtest.py#L223

**Comment by rsyring** [comment]
I'm going to close this due to age.  Feel free to re-open if the problem persists and you can provide a small test case.
