### ISSUE TITLE
Transfer ownership of project

### ISSUE THREAD

**Issue by rsyring** [level12/flask-webtest#16]
@aromanovich just wanted to get out in public that you are transferring the repository to me.  I was able to accept the PyPI invite but missed the GitHub email and it has expired.  Will you try again?

When finished we will integrate our changes at https://github.com/level12/flask-webtest back into the main project.

@guruofgentoo: I'd normally accept this ownership transfer on GH and put it in our level12 org.  However, we already have our fork there and that's going to cause a name clash.  :o/

**Comment by rsyring** [comment]
This repo is the official repo that was transferred to us and I deleted the fork that used to exist in our level12 org.  Prior to deleting that fork I moved @guruofgentoo commits to this repo.

@aromanovich looks like we will need Read the Docs project access as well.

**Comment by guruofgentoo** [comment]
Pinged @aromanovich via email for adding me on the readthedocs project.
